declare @seccion_PRODUCTOS_INALECSA uniqueidentifier 
declare @seccion_EXHIBIDORES_INALECSA uniqueidentifier 
declare @seccion_MATERIAL_POP uniqueidentifier 
declare @seccion_Observaciones uniqueidentifier 
declare @seccion_INFORMACIÓN_DEL_LOCAL uniqueidentifier 

declare @subseccion_PRODUCTOS_INALECSA_INACAKE uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_INACAKE_RELLENO uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_CHOCOCAKE uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_GANSITOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_REBANADAS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TIGRETON uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_BONY uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TOSTITOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_JALAPEÑOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_RYSCOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_NACHOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TORNADITOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_PIZZEROLAS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TOSTACHOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_SARITAS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TORTOLINES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_RONDITOS uniqueidentifier 
declare @subseccion_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES uniqueidentifier 
declare @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR uniqueidentifier 
declare @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO uniqueidentifier 
declare @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO uniqueidentifier 
declare @subseccion_MATERIAL_POP_BANDEROLA_INALECSA uniqueidentifier 
declare @subseccion_MATERIAL_POP_EN_EL_EXTERIOR uniqueidentifier 

declare @pregunta_PRODUCTOS_INALECSA_INACAKE_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_GANSITOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_REBANADAS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TIGRETON_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_BONY_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_RYSCOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_NACHOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_SARITAS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_RONDITOS_EXISTE uniqueidentifier 
declare @pregunta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_CANTIDAD uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_porcentaje uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_CANTIDAD uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_porcentaje uniqueidentifier 
declare @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE uniqueidentifier 
declare @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION uniqueidentifier 
declare @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_CANTIDAD uniqueidentifier 
declare @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO uniqueidentifier 
declare @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_porcentaje uniqueidentifier 

declare @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_NO uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_SI uniqueidentifier 
declare @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_NO uniqueidentifier
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_CANTIDAD_NULL uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_porcentaje_NULL uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_si uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_no uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_CANTIDAD_NULL uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_porcentaje_NULL uniqueidentifier 
declare @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_SI uniqueidentifier 
declare @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_NO uniqueidentifier 
declare @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_SI uniqueidentifier 
declare @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_NO uniqueidentifier 
declare @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_SI uniqueidentifier 
declare @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_CANTIDAD_NULL uniqueidentifier 
declare @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_SI uniqueidentifier 
declare @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_SI uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_NO uniqueidentifier 
declare @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_porcentaje_NULL uniqueidentifier 

declare @pregunta_INFORMACIÓN_DEL_LOCAL_LOCAL uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_DIRECCION uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_TIPOLOGIA uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_REFERENCIA uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_NOMBRE_PROPIETARIO uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_ESTADO uniqueidentifier 
declare @pregunta_INFORMACIÓN_DEL_LOCAL_CODIGO_MARDIS uniqueidentifier 
declare @pregunta_Observaciones_OBSERVACIONES uniqueidentifier 



set @seccion_PRODUCTOS_INALECSA = '1EB12A57-68D6-4643-0784-08D47D2B13E1'
set @seccion_EXHIBIDORES_INALECSA = '711414ED-F57A-4A67-3C75-08D47DBBC58F'
set @seccion_MATERIAL_POP = 'A3926281-A8DF-4E4E-3C79-08D47DBBC58F'
set @seccion_Observaciones = '6F07C4FF-FDBA-40DE-3C7C-08D47DBBC58F'
set @seccion_INFORMACIÓN_DEL_LOCAL = '6FD8C757-B724-4F35-B6CF-FA3C5A5C2EE7'

set @subseccion_PRODUCTOS_INALECSA_INACAKE = '974240C9-DCB4-47B1-0785-08D47D2B13E1'
set @subseccion_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES = '2E83285D-18FE-4139-0786-08D47D2B13E1'
set @subseccion_PRODUCTOS_INALECSA_INACAKE_RELLENO = 'AEEEFC31-8734-4388-0787-08D47D2B13E1'
set @subseccion_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES = '656EBB48-76BE-4315-3D43-08D47DBAE790'
set @subseccion_PRODUCTOS_INALECSA_CHOCOCAKE = '9458DCE0-9B43-455D-3C58-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES = 'D5055E8F-6FDA-4D8D-3C59-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_GANSITOS = 'FDEF9CAF-1176-413A-3C5A-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES = 'DCC831D2-AE0B-433E-3C5B-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_REBANADAS = '7A17214D-7570-4CA5-3C5C-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES = '0719B6DC-663B-4331-3C5D-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TIGRETON = '4E970312-BD04-4061-3C5E-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES = '1B20A1E1-7545-421A-3C5F-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_BONY = '2F758C82-983C-4226-3C60-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES = '7B74A801-076F-4114-3C61-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TOSTITOS = '9E1EF562-78DD-4726-3C62-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES = '816F5BB1-96FD-4B3F-3C63-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_JALAPEÑOS = 'DCA6D38D-BCAC-4115-3C64-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES = '32704090-BC73-4286-3C65-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_RYSCOS = 'F5C90460-7BA8-4A79-3C66-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES = 'BE722C85-7145-49EC-3C67-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_NACHOS = '9046AD79-FAEA-42EB-3C68-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES = 'D503F46C-340E-4645-3C69-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TORNADITOS = '6C201433-73AA-4991-3C6A-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES = '3C01F047-0CE9-406A-3C6B-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_PIZZEROLAS = 'DCB6F0B6-6C28-4EC2-3C6C-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES = '7E573D3A-D3E1-4EA4-3C6D-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TOSTACHOS = 'B44AC45B-F2ED-4C4C-3C6E-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES = 'E02C69BF-7E7E-4FE6-3C6F-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_SARITAS = '12BACF32-E80F-4E60-3C70-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES = '62342976-B678-4D46-3C71-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TORTOLINES = '24E747B7-4A1D-4D77-3C72-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES = '5278478A-8133-4CE7-3C73-08D47DBBC58F'
set @subseccion_PRODUCTOS_INALECSA_RONDITOS = 'C2C7623D-9CD0-4003-856E-91CC7EFFEF52'
set @subseccion_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES = 'CE5A0DB1-220A-4428-B781-262175296107'
set @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR = '009E6BCB-3F77-4003-3C76-08D47DBBC58F'
set @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO = '41FB2991-E4A8-4F6C-3C77-08D47DBBC58F'
set @subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO = 'DCE1D1EE-9D09-414C-3C78-08D47DBBC58F'
set @subseccion_MATERIAL_POP_BANDEROLA_INALECSA = 'E07426A1-8C12-40AF-3C7B-08D47DBBC58F'
set @subseccion_MATERIAL_POP_EN_EL_EXTERIOR = 'C7E600D7-DFCE-4AAC-3C7A-08D47DBBC58F'

set @pregunta_PRODUCTOS_INALECSA_INACAKE_EXISTE = 'E1B898E7-C7EA-4F74-84C9-08D47D2B6768'
set @pregunta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE = 'B110F718-A7D8-45C2-84CA-08D47D2B6768'
set @pregunta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE = '45D22A6B-FF1A-406E-84CB-08D47D2B6768'
set @pregunta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE = '1B48AD2D-15C3-4B8C-23F7-08D47DBAE793'
set @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE = '31471D2C-C9A5-44AC-30C0-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE = 'D04DFC99-1C49-40F1-30C1-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_GANSITOS_EXISTE = 'EC723FA4-697A-4D74-30C2-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE = '872CE4D6-2E9C-46F0-30C3-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_REBANADAS_EXISTE = '7BCFFFDA-FCED-45FA-30C4-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE = 'B1804509-0D8F-4942-30C5-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TIGRETON_EXISTE = '7852A8E6-B06D-4A3E-30C6-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE = '7FFEB81A-4808-488B-30C7-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_BONY_EXISTE = '0660C423-008E-4A22-30C8-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE = '2B873386-7A5E-483B-30C9-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE = 'D07FCE91-00C6-4F9B-30CA-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE = '8CAA800E-702D-4AD1-30CB-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE = 'E9DCAC1D-6EE0-4911-30CC-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE = '498FCCBC-16F8-40FD-30CD-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_RYSCOS_EXISTE = '45899C01-C068-4D6A-30CE-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE = 'AC1C8FAE-A968-4B23-30CF-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_NACHOS_EXISTE = 'A52B097D-9543-41E1-30D0-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE = 'C33641E3-170A-415F-30D1-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE = 'A80280C1-0F9D-4AAB-30D2-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE = 'DC7DB3F4-A48E-497A-30D3-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE = '5EEFF222-6FD6-4AAA-30D4-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE = 'FC336BD6-ECBD-462B-30D5-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE = 'DC7F5882-BE36-4239-30D6-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE = '221D6122-68A1-44C8-30D7-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_SARITAS_EXISTE = '379B72FE-CC75-42C8-30D8-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE = '03C7A830-DE89-4BD5-30D9-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE = 'C86A408B-16B3-426C-30DA-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE = '9159CA44-D93A-472D-30DB-08D47DBBC595'
set @pregunta_PRODUCTOS_INALECSA_RONDITOS_EXISTE = '681BE1D4-58D9-49B5-8508-A83B0B3A1EF4'
set @pregunta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE = 'E0E3B6C4-602F-49E5-B8BA-766E1AD7B7F5'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE = 'AB5255C5-3D91-4E56-30DD-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE = '78209200-A441-42EA-30DE-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION = '27251EAC-C789-4BA3-30DF-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO = 'CBBEF557-E6CB-4972-30E0-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_CANTIDAD = '8F11635C-6F9C-414F-30E1-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO = '6679C365-3548-4118-30E2-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_porcentaje = '859F3CF8-10E3-4E63-30E3-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE = '4168631B-5B9B-467B-30E4-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION = '02B5402A-7A45-45D3-30E5-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO = '4316C7C4-A6BE-46D6-30E6-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_CANTIDAD = '41D620D2-AFE3-494B-30E7-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO = '51CDACFB-16EA-405A-30E8-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_porcentaje = 'F3F3A776-DC7A-40F1-30E9-08D47DBBC595'
set @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE = '45C2C05A-A6A6-4F2C-30EB-08D47DBBC595'
set @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO = 'FDBCA81A-EE5F-4BBD-30EC-08D47DBBC595'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION = '9DB68131-6B57-49FE-BE6E-273C3B4EAFA2'
set @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE = '299C8E6D-7498-44EC-AC50-3BD1CB6DFFE6'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO = 'D7CE236A-0AD8-4978-B75D-53DC2DA8512C'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_CANTIDAD = 'A4163E7A-E7BA-4A2B-9D11-743642ED31FC'
set @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO = 'E11382E3-8047-4CDF-AAC7-7DCE03FC779E'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO = '7C2A34A1-A294-4FCD-AEF9-89F644A11337'
set @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_porcentaje = '37877544-FE3F-4A51-9B74-A39626325375'

set @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_SI = 'F5A7BED0-A802-4184-4292-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_NO = 'E2FD1526-A379-47A2-4293-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_SI = '73AB660A-E2FB-45AC-4294-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_NO = 'ACF2D499-4940-4985-4295-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE_SI = '990AB927-0F06-4A8F-4296-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_EXISTE_NO = '9349B322-0F6D-43F4-4297-08D47DBA7D28'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE_SI = 'B104E3EF-888A-44E9-F901-08D47DBAE794'
set @respuesta_PRODUCTOS_INALECSA_INACAKE_RELLENO_DE_3_UNIDADES_EXISTE_NO = '48A49112-DB5A-42F0-F902-08D47DBAE794'
set @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_SI = 'E73360ED-A68F-4354-F068-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_NO = '1F593D95-FD52-44BC-F069-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_SI = 'E82E796C-11B5-4BCA-F06A-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_NO = '926392A4-5CF9-4D1D-F06B-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_SI = 'D231089B-FEDA-44E6-F06C-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_NO = 'BF3F9E74-1960-4B76-F06D-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_SI = 'A383FDFE-9F43-438E-F06E-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_NO = '31A9B069-B025-446A-F06F-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_SI = '22EC4DCC-699F-4875-F070-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_NO = 'A1019190-30B2-4AC0-F071-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_SI = 'E30A0820-49DE-4EE7-F072-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_NO = 'E51A0A7F-BAEE-4056-F073-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_SI = 'CC1F9795-B77B-458B-F074-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_NO = 'F0B1DB66-0049-4E24-F075-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_SI = 'D479DD3A-6F49-482B-F076-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_NO = 'CDEADA08-051F-4EAE-F077-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_SI = '2375998C-2562-4C78-F078-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_NO = 'D469A979-0E47-4F31-F079-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_SI = '868B2BFF-F84E-4A6B-F07A-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_NO = '1AE6A8AA-582E-4BDF-F07B-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_SI = '5DCD11BA-ACE4-46E7-F07C-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_NO = '6E57CF23-774B-4A75-F07D-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_SI = 'A527746F-F0E8-4F00-F07E-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_NO = 'E68888F3-0904-4CA1-F07F-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_SI = '921F6D44-FB61-4E55-F080-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_NO = 'B261BF76-7F2E-486D-F081-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_SI = '48BACC92-23C9-4255-F082-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_NO = '0E114D47-DBE6-4F59-F083-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_SI = '411CBF7C-475E-4164-F084-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_NO = 'E347D4FE-128D-46F8-F085-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_SI = '1A79BF04-ACD5-4435-F086-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_NO = '4D8CB856-FCC2-4511-F087-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_SI = '9F613098-3109-4718-F088-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_NO = '5636EE5C-8732-4649-F089-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_SI = '20818C77-76F0-45EA-F08A-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_NO = '683737F1-4C9F-4C37-F08B-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_SI = 'ADDE5912-B723-4746-F08C-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_NO = '248CD899-F3B3-470D-F08D-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_SI = '9E26E65C-11E2-4AE9-F08E-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_NO = '0C120A03-EB82-481B-F08F-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_SI = '440387AD-4320-43A6-F090-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_NO = '3627848A-4C45-480C-F091-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_SI = 'A6FE0405-6270-4FA7-F092-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_NO = '73ECFC03-725D-40E9-F093-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_SI = '77422FF7-F047-4A17-F094-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_NO = 'F21E2103-6674-40F1-F095-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_SI = '5E9C9526-2643-473F-F096-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_NO = '0444BE9E-B333-4869-F097-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_SI = '6390964B-2C26-41B6-F098-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_NO = '672B224F-5271-4ADD-F099-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_SI = '5FDF282A-98E2-454E-F09A-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_NO = 'CAF2939C-F501-49C4-F09B-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_SI = 'A9F3AC04-6579-45BD-F09C-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_NO = 'A255224F-27D6-4F61-F09D-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_SI = '6E6435D8-1659-4013-F09E-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_NO = '85788CC8-60EE-4A8B-F09F-08D47DBBC597'
set @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_SI = '2ED1CE0F-55EB-41AA-8376-D0D9A74B0975'
set @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_NO = '261639C5-FA9A-42EA-9E0C-D7B7E565C4CD'
set @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_SI = '5DA7C6C1-AC34-4C72-94AE-C37CC0B6AB53'
set @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_NO = '20F0789A-DB8C-4CAF-9D69-36495678B7A4'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_SI = '0965FFCF-8D4F-424D-F0A2-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_NO = '6EE2218A-A479-4266-F0A3-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_SI = 'FF6A313B-BB08-43A5-F0A4-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_NO = 'BA1CDE99-EA31-4F46-F0A5-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_SI = '67CA0C2B-D268-4CC6-F0A6-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_NO = '86B611F3-8499-4AA2-F0A7-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_SI = '0B5ADECC-7BB3-4A02-F0A8-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_NO = '3A3E375F-D7C0-4494-F0A9-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_SI = 'A090F5D7-D816-4296-F0AA-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_NO = 'F8896729-C02E-4EF8-F0AB-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_SI = '3C83B6C7-D5A5-4E55-F0AC-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_NO = '538033E1-93B3-4B2D-F0AD-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_si = 'E8FF9191-1A51-4F2D-F0AE-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_no = '54BC792B-53AE-4770-F0AF-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_SI = '26597579-D71A-4EFC-F0B0-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_NO = '451A7170-4119-4718-F0B1-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_SI = '4FFB7F16-A1EA-445E-F0B2-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_NO = '4C3633BE-AEEC-4598-F0B3-08D47DBBC597'
set @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_SI = '40CC5206-698B-4043-F0B4-08D47DBBC597'
set @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_NO = 'D44CC9CF-B29A-47D9-F0B5-08D47DBBC597'
set @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_SI = 'D6772C60-0E44-4257-F0B6-08D47DBBC597'
set @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_NO = '4BDBE2BF-7E34-47F4-F0B7-08D47DBBC597'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_SI = '7AB864CC-0A3C-4299-9DDA-1BB4C275AF7A'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_NO = '9E533337-C708-4931-B331-BEBB2E275AF2'
set @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_SI = '58FE40F8-5CD1-4DBE-BB34-544581DCE9BB'
set @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_NO = '56172DD7-601E-4D5C-8134-C8B294F253A0'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_SI = 'CA43E7BB-EE80-46A3-ADDE-88F4271152D7'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_NO = 'D7AA04F0-6267-4C3A-94A6-B9581F2E3D9F'
set @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_SI = '0156E067-6F96-4A64-873E-2F611CA5A0B4'
set @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_NO = '6809C9CD-CFBC-44D0-AFFB-940FDFE76930'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_SI = '83A1AD04-A8B0-43A5-AFFA-2EF850E23B2A'
set @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_NO = '9E5FBBDD-4451-40C6-890E-9F9713757CFE'

set @pregunta_INFORMACIÓN_DEL_LOCAL_LOCAL = '65D00879-5FE2-41D6-BA4F-3C8A1FD4BFCF'
set @pregunta_INFORMACIÓN_DEL_LOCAL_DIRECCION = '93C96E49-C4B2-4111-A753-41FC3DC5F539'
set @pregunta_INFORMACIÓN_DEL_LOCAL_TIPOLOGIA = 'CAD63F3D-7262-4CFE-A6F0-5A4375DA0F57'
set @pregunta_INFORMACIÓN_DEL_LOCAL_REFERENCIA = '050CDFD6-8954-4565-8D50-5AF0DE0AB023'
set @pregunta_INFORMACIÓN_DEL_LOCAL_NOMBRE_PROPIETARIO = '55FFCF42-93EF-421E-97B1-75C06E7FE247'
set @pregunta_INFORMACIÓN_DEL_LOCAL_ESTADO = '904C373D-7149-43AF-9B37-7B0FB405C6D0'
set @pregunta_INFORMACIÓN_DEL_LOCAL_CODIGO_MARDIS = 'BD149E9C-68DA-45FD-A199-8EB4669253B0'
set @pregunta_Observaciones_OBSERVACIONES = 'F7021D2D-3951-4D5E-9293-AE5A40543AFB'

declare @estado varchar(10),					@codigo_mardis varchar(10),					@tipologia varchar(10),						@local varchar(10),							@nombre varchar(10),						@direccion varchar(10),
		@referencia varchar(10),				@obervacion varchar(10),					@inacake varchar(10),						@inacake_mas_de_3_unidades varchar(10),		@chocokake varchar(10),						@chocokake_mas_de_3_unidades varchar(10),
		@gansitos varchar(10),					@gansitos_mas_de_3_unidades varchar(10),	@bony varchar(10),							@bony_mas_de_3_unidades varchar(10),		@rabanadas varchar(10),						@rabanadas_mas_de_3_unidades varchar(10),
		@tigreton varchar(10),					@tigreton_mas_de_3_unidades varchar(10),	@tostitos varchar(10),						@tostitos_mas_de_3_unidades varchar(10),	@zarita varchar(10),						@zarita_mas_de_3_unidades varchar(10),
		@pizzerolas varchar(10),				@pizzerolas_mas_de_3_unidades varchar(10),	@tortolines varchar(10),					@tortolines_mas_de_3_unidades varchar(10),	@ronditos varchar(10),						@ronditos_mas_de_3_unidades varchar(10),
		@jalapeños varchar(10),					@jalapeños_mas_de_3_unidades varchar(10),	@ryscos varchar(10),						@ryscos_mas_de_3_unidades varchar(10),		@tostachos varchar(10),						@tostachos_mas_de_3_unidades varchar(10),
		@tornaditos varchar(10),				@tornaditos_mas_de_3_unidades varchar(10),	@nachos varchar(10),						@nachos_mas_de_3_unidades varchar(10),		@tiene_exhibidor_de_mostrador varchar(10),	@cantidad_mostrador varchar(10),
		@porc__mostrador varchar(10),			@primera_posicion__mostrador varchar(10),	@producto_extraño__mostrador varchar(10),	@en_buen_estado__mostrador varchar(10),		@tiene_exhibidor_fijo varchar(10),			@cantidad_fijo varchar(10),
		@porc_fijo varchar(10),					@primera_posicion_fijo varchar(10),			@producto_extraño_fijo varchar(10),			@en_buen_estado_fijo varchar(10),			@tiene_exhibidor_aéreo varchar(10),			@cantidad_aéreo varchar(10),
		@porc_aéreo varchar(10),				@primera_posicion_aéreo varchar(10),		@producto_extraño_aéreo varchar(10),		@en_buen_estado_aéreo varchar(10),			@tiene_pop_en_el_exterior varchar(10),		@en_buen_estado_pop varchar(10),
		@tiene_banderola_inalecsa varchar(10),	@en_buen_estado_caserola varchar(10),		@ruta varchar(10)



--select * from formulario_inalecsa
declare cur_formulario cursor for
   SELECT	[ESTADO]						,[CODIGO MARDIS]				,[TIPOLOGIA]					,[LOCAL]						,[NOMBRE]						,[DIRECCION]      
			,[REFERENCIA]					,[OBERVACION]					,[INACAKE]						,[INACAKE MAS DE TRES]			,[CHOCOKAKE]					,[CHOCOKAKE MAS DE TRES]      
			,[GANSITOS]						,[GANSITOS MAS DE TRES]			,[BONY]							,[BONY MAS DE TRES]				,[RABANADAS]					,[RABANADAS MAS DE TRES]      
			,[TIGRETON]						,[TIGRETON MAS DE TRES]			,[TOSTITOS]						,[TOSTITOS MAS DE TRES]			,[ZARITA]						,[ZARITA MAS DE TRES]      
			,[PIZZEROLAS]					,[PIZZEROLAS MAS DE TRES]		,[TORTOLINES]					,[TORTOLINES MAS DE TRES]		,[RONDITOS]						,[RONDITOS MAS DE TRES]      
			,[JALAPEÑOS]					,[JALAPEÑOS MAS DE TRES]		,[RYSCOS]						,[RYSCOS MAS DE TRES]			,[TOSTACHOS]					,[TOSTACHOS MAS DE TRES]      
			,[TORNADITOS]					,[TORNADITOS MAS DE TRES]		,[NACHOS]						,[NACHOS MAS DE TRES]			,[Tiene Exhibidor de Mostrador] ,[CANTIDAD MOSTRADOR]      
			,[% MOSTRADOR]					,[PRIMERA POSICION MOSTRADOR]   ,[PRODUCTO EXTRAÑO MOSTRADOR]   ,[EN BUEN ESTADO MOSTRADOR]     ,[Tiene Exhibidor Fijo]			,[CANTIDAD Fijo]      
			,[% Fijo]						,[PRIMERA POSICION Fijo]		,[PRODUCTO EXTRAÑO Fijo]		,[EN BUEN ESTADO Fijo]			,[Tiene Exhibidor Aéreo]		,[CANTIDAD Aéreo]     
			,[% Aéreo]						,[PRIMERA POSICION Aéreo]		,[PRODUCTO EXTRAÑO Aéreo]		,[EN BUEN ESTADO Aéreo]			,[TIENE POP EN EL EXTERIOR]     ,[EN BUEN ESTADO POP]      
			,[TIENE BANDEROLA INALECSA]		,[EN BUEN ESTADO BANDEROLA]     ,[RUTA]
	FROM [dbo].[FORMULARIO_INALECSA]
	WHERE ESTADO ='OK'

open cur_formulario

fetch next from cur_formulario into @estado,					@codigo_mardis,					@tipologia,						@local,							@nombre,						@direccion,
									@referencia,				@obervacion ,					@inacake ,						@inacake_mas_de_3_unidades ,	@chocokake ,					@chocokake_mas_de_3_unidades ,
									@gansitos ,					@gansitos_mas_de_3_unidades ,	@bony ,							@bony_mas_de_3_unidades ,		@rabanadas ,					@rabanadas_mas_de_3_unidades ,
									@tigreton ,					@tigreton_mas_de_3_unidades ,	@tostitos ,						@tostitos_mas_de_3_unidades ,	@zarita ,						@zarita_mas_de_3_unidades ,
									@pizzerolas ,				@pizzerolas_mas_de_3_unidades ,	@tortolines ,					@tortolines_mas_de_3_unidades ,	@ronditos ,						@ronditos_mas_de_3_unidades ,
									@jalapeños ,				@jalapeños_mas_de_3_unidades ,	@ryscos ,						@ryscos_mas_de_3_unidades ,		@tostachos ,					@tostachos_mas_de_3_unidades ,
									@tornaditos ,				@tornaditos_mas_de_3_unidades ,	@nachos ,						@nachos_mas_de_3_unidades ,		@tiene_exhibidor_de_mostrador ,	@cantidad_mostrador ,
									@porc__mostrador,			@primera_posicion__mostrador ,	@producto_extraño__mostrador ,	@en_buen_estado__mostrador ,	@tiene_exhibidor_fijo ,			@cantidad_fijo ,
									@porc_fijo ,				@primera_posicion_fijo ,		@producto_extraño_fijo ,		@en_buen_estado_fijo ,			@tiene_exhibidor_aéreo ,		@cantidad_aéreo ,
									@porc_aéreo ,				@primera_posicion_aéreo ,		@producto_extraño_aéreo ,		@en_buen_estado_aéreo ,			@tiene_pop_en_el_exterior ,		@en_buen_estado_pop ,
									@tiene_banderola_inalecsa ,	@en_buen_estado_caserola,		@ruta

while(@@FETCH_STATUS=0)
begin

	if exists(select 1 from MardisCore.Branch where IdAccount='BDC6AD75-07B6-4B49-561F-08D47D26C3E1' and ExternalCode=@codigo_mardis)
	begin
		declare @branch uniqueidentifier,
				@task uniqueidentifier,
				@hora_actual datetime

		select @branch = id from MardisCore.Branch where IdAccount='BDC6AD75-07B6-4B49-561F-08D47D26C3E1' and ExternalCode=@codigo_mardis

		set @task=NEWID()

		set @hora_actual = getdate()
		--creo la tarea 
		exec sp_insert_task	   @Id = @task OUTPUT
								,@IdAccount = 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1'
								,@Code = 'TAR-'
								,@DateCreation = @hora_actual
								,@IdCampaign = 'C0C8AEAE-D5B1-4E13-7506-08D47DBE6EFD'
								,@StartDate = @hora_actual
								,@Description = 'Tarea migrada desde bases Aggregate'
								,@IdBranch = @branch
								,@IdMerchant = '1425DDBC-81DF-4422-AF46-39498A411F29'
								,@StatusRegister = 'A'
								,@IdStatusTask = '769087E2-4AE6-44F3-871F-291DB934431D'
								,@CommentTaskNoImplemented = ''
								,@IdTaskNoImplementedReason = null
								,@Route = @ruta
								,@DateModification = @hora_actual
								,@ExternalCode = null
								,@AggregateUri = null

		--

		declare @respuesta_actual uniqueidentifier,
					@pregunta_actual uniqueidentifier,
					@seccion_actual uniqueidentifier,
					@opcion_respuesta_actual uniqueidentifier
		
		-----------------------------------------------------------------------------SECCIÓN INFORMACION DE LOCAL--------------------------------------------------------------
		set @seccion_actual=@seccion_INFORMACIÓN_DEL_LOCAL

		--ESTADO
		if(@estado is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @estado,null
					)
		end

		--CODIGO MARDIS
		if(@codigo_mardis is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_CODIGO_MARDIS
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @codigo_mardis,null
					)
		end

		--tipologia
		if(@tipologia is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_TIPOLOGIA
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @tipologia,null
					)
		end

		--local
		if(@local is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_LOCAL
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @local,null
					)
		end

		--nombre
		if(@nombre is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_NOMBRE_PROPIETARIO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @nombre,null
					)
		end

		--dirección
		if(@direccion is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_DIRECCION
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)


					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @direccion,null
				)
		end

		--referencia
		if(@referencia is not null)
		begin
			set @pregunta_actual = @pregunta_INFORMACIÓN_DEL_LOCAL_REFERENCIA
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
				insert into mardiscore.AnswerDetail values
					(
						newid(), null, getdate(), @respuesta_actual, 'A', 0, @referencia,null
					)
		end

		-----------------------------------------------------------------------------SECCIÓN PRODUCTOS INALECSA--------------------------------------------------------------
		--inacake
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_INACAKE
		if(@inacake is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_INACAKE_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_SI

			if(@inacake='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_INACAKE_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--inacake + de 3
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES
		if(@inacake_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_SI

			if(@inacake_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_INACAKE_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--chococake
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_CHOCOCAKE
		if(@chocokake is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_SI

			if(@chocokake='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--chococake mas de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES
		if(@chocokake_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_SI

			if(@chocokake_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_CHOCOCAKE_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--gansitos
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_GANSITOS
		if(@gansitos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_GANSITOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_SI

			if(@gansitos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_GANSITOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--gansitos + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES
		if(@gansitos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_SI

			if(@gansitos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_GANSITOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--bony
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_BONY
		if(@bony is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_BONY_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_SI

			if(@bony='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_BONY_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--bony + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES
		if(@bony_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_SI

			if(@bony_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_BONY_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--rebanadas
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_REBANADAS
		if(@rabanadas is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_REBANADAS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_SI

			if(@rabanadas='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_REBANADAS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--rebanadas + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES
		if(@rabanadas_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_SI

			if(@rabanadas_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_REBANADAS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tigreton
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TIGRETON
		if(@tigreton is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TIGRETON_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_SI

			if(@tigreton='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TIGRETON_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tigreton + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES
		if(@tigreton_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_SI

			if(@tigreton_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TIGRETON_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		-----------------------------------------------------------------------------SECCIÓN skacks INALECSA--------------------------------------------------------------
		--tostitos
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TOSTITOS
		if(@tostitos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_SI

			if(@tostitos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTITOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tostitos + de 3
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES
		if(@tostitos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_SI

			if(@tostitos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTITOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--RONDITOS
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_RONDITOS
		if(@ronditos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_RONDITOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_SI

			if(@ronditos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RONDITOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--RONDITOS + de 3
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES
		if(@ronditos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_SI

			if(@ronditos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RONDITOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--saritas
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_SARITAS
		if(@zarita is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_SARITAS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_SI

			if(@zarita='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_SARITAS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--saritas + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES
		if(@zarita_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_SI

			if(@zarita_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_SARITAS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--pizzerolas
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_PIZZEROLAS
		if(@pizzerolas is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_SI

			if(@pizzerolas='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--pizzerolas + de 3
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES
		if(@pizzerolas_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_SI

			if(@pizzerolas_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_PIZZEROLAS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tortolines
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TORTOLINES
		if(@tortolines is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_SI

			if(@tortolines='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORTOLINES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tortolines + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES
		if(@tortolines_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_SI

			if(@tortolines_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORTOLINES_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--jalapeños
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_JALAPEÑOS
		if(@jalapeños is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_SI

			if(@jalapeños='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--jalapeños + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES
		if(@jalapeños_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_SI

			if(@jalapeños_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_JALAPEÑOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--ryskos
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_RYSCOS
		if(@ryscos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_RYSCOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_SI

			if(@ryscos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RYSCOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--ryscos + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES
		if(@ryscos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_SI

			if(@ryscos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_RYSCOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tostachos
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TOSTACHOS
		if(@tostachos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_SI

			if(@tostachos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tostachos + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES
		if(@tostachos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_SI

			if(@tostachos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TOSTACHOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tornados
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TORNADITOS
		if(@tornaditos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_SI

			if(@tornaditos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORNADITOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--tornaditos + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES
		if(@tornaditos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_SI

			if(@tornaditos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_TORNADITOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--nachos
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_NACHOS
		if(@nachos is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_NACHOS_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_SI

			if(@nachos='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_NACHOS_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--nachos + de tres
		set @seccion_actual=@subseccion_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES
		if(@nachos_mas_de_3_unidades is not null)
		begin
			set @pregunta_actual = @pregunta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_SI

			if(@nachos_mas_de_3_unidades='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_PRODUCTOS_INALECSA_NACHOS_DE_3_UNIDADES_EXISTE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		----------------------------------------------------------------------------------------SECCIÓN EXHIBIDORES INALECSA---------------------------------------------------------------
		--EXHIBIDOR FIJO
		set @seccion_actual=@subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO
		if(@tiene_exhibidor_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_SI

			if(@tiene_exhibidor_fijo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_TIENE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@cantidad_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_CANTIDAD
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @cantidad_fijo,null
				)
		end

		if(@porc_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_porcentaje
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @porc_fijo,null
				)
		end

		if(@primera_posicion_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_SI

			if(@primera_posicion_fijo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRIMERA_POSICION_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@producto_extraño_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_SI

			if(@producto_extraño_fijo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_PRODUCTO_EXTRAÑO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@en_buen_estado_fijo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_SI

			if(@en_buen_estado_fijo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_FIJO_EN_BUEN_ESTADO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--mostrador
		set @seccion_actual=@subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR
		if(@tiene_exhibidor_de_mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_SI

			if(@tiene_exhibidor_de_mostrador='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_TIENE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@cantidad_mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_CANTIDAD
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @cantidad_mostrador,null
				)
		end

		if(@porc__mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_porcentaje
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @porc__mostrador,null
				)
		end

		if(@primera_posicion__mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_SI

			if(@primera_posicion__mostrador='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRIMERA_POSICION_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@producto_extraño__mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_SI

			if(@producto_extraño__mostrador='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_PRODUCTO_EXTRAÑO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@en_buen_estado__mostrador is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_SI

			if(@en_buen_estado__mostrador='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_DE_MOSTRADOR_EN_BUEN_ESTADO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--aereo
		set @seccion_actual=@subseccion_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO
		if(@tiene_exhibidor_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_SI

			if(@tiene_exhibidor_aéreo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_TIENE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@cantidad_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_CANTIDAD
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @cantidad_aéreo,null
				)
		end

		if(@porc_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_porcentaje
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), null, getdate(), @respuesta_actual, 'A', 0, @porc_aéreo,null
				)
		end

		if(@primera_posicion_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_si

			if(@primera_posicion_aéreo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRIMERA_POSICION_no
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@producto_extraño_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_SI

			if(@producto_extraño_aéreo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_PRODUCTO_EXTRAÑO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@en_buen_estado_aéreo is not null)
		begin
			set @pregunta_actual = @pregunta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_SI

			if(@en_buen_estado_aéreo='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_EXHIBIDORES_INALECSA_EXHIBIDOR_AÉREO_EN_BUEN_ESTADO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		----------------------------------------------------------------------------------------SECCIÓN POP INALECSA---------------------------------------------------------------
		--pop exterior
		set @seccion_actual=@subseccion_MATERIAL_POP_EN_EL_EXTERIOR
		if(@tiene_pop_en_el_exterior is not null)
		begin
			set @pregunta_actual = @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_SI

			if(@tiene_pop_en_el_exterior='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_TIENE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@en_buen_estado_pop is not null)
		begin
			set @pregunta_actual = @pregunta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_SI

			if(@tiene_pop_en_el_exterior='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_EN_EL_EXTERIOR_EN_BUEN_ESTADO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		--banderola inalecsa
		set @seccion_actual=@subseccion_MATERIAL_POP_BANDEROLA_INALECSA
		if(@tiene_banderola_inalecsa is not null)
		begin
			set @pregunta_actual = @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_SI

			if(@tiene_banderola_inalecsa='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_TIENE_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

		if(@en_buen_estado_caserola is not null)
		begin
			set @pregunta_actual = @pregunta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO
			set @respuesta_actual=newid()

			insert into MardisCore.Answer values
					(
						@respuesta_actual, 'BDC6AD75-07B6-4B49-561F-08D47D26C3E1', @task, getdate(), @seccion_actual, '1425DDBC-81DF-4422-AF46-39498A411F29',
						@pregunta_actual, 'A'
					)

			set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_SI

			if(@tiene_pop_en_el_exterior='NO')
			begin
				set @opcion_respuesta_actual = @respuesta_MATERIAL_POP_BANDEROLA_INALECSA_EN_BUEN_ESTADO_NO
			end
					
			insert into mardiscore.AnswerDetail values
				(
					newid(), @opcion_respuesta_actual, getdate(), @respuesta_actual, 'A', 0, NULL,null
				)
		end

	end
	else
	begin
		print 'no encontré local'
	end
	
	fetch next from cur_formulario into @estado,					@codigo_mardis,					@tipologia,						@local,							@nombre,						@direccion,
										@referencia,				@obervacion ,					@inacake ,						@inacake_mas_de_3_unidades ,	@chocokake ,					@chocokake_mas_de_3_unidades ,
										@gansitos ,					@gansitos_mas_de_3_unidades ,	@bony ,							@bony_mas_de_3_unidades ,		@rabanadas ,					@rabanadas_mas_de_3_unidades ,
										@tigreton ,					@tigreton_mas_de_3_unidades ,	@tostitos ,						@tostitos_mas_de_3_unidades ,	@zarita ,						@zarita_mas_de_3_unidades ,
										@pizzerolas ,				@pizzerolas_mas_de_3_unidades ,	@tortolines ,					@tortolines_mas_de_3_unidades ,	@ronditos ,						@ronditos_mas_de_3_unidades ,
										@jalapeños ,				@jalapeños_mas_de_3_unidades ,	@ryscos ,						@ryscos_mas_de_3_unidades ,		@tostachos ,					@tostachos_mas_de_3_unidades ,
										@tornaditos ,				@tornaditos_mas_de_3_unidades ,	@nachos ,						@nachos_mas_de_3_unidades ,		@tiene_exhibidor_de_mostrador ,	@cantidad_mostrador ,
										@porc__mostrador,			@primera_posicion__mostrador ,	@producto_extraño__mostrador ,	@en_buen_estado__mostrador ,	@tiene_exhibidor_fijo ,			@cantidad_fijo ,
										@porc_fijo ,				@primera_posicion_fijo ,		@producto_extraño_fijo ,		@en_buen_estado_fijo ,			@tiene_exhibidor_aéreo ,		@cantidad_aéreo ,
										@porc_aéreo ,				@primera_posicion_aéreo ,		@producto_extraño_aéreo ,		@en_buen_estado_aéreo ,			@tiene_pop_en_el_exterior ,		@en_buen_estado_pop ,
										@tiene_banderola_inalecsa ,	@en_buen_estado_caserola,		@ruta 
end

close cur_formulario
deallocate cur_formulario