//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("FilterController", Schema = "MardisCore")]
    public partial class FilterController : IEntity
    {
      
        public FilterController()
        {
            this.FilterFields = new HashSet<FilterField>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public string NameController { get; set; }
        public string NameTable { get; set; }
        public string HasStatus { get; set; }
        public string HasAccount { get; set; }



        public virtual ICollection<FilterField> FilterFields { get; set; }
        public virtual ICollection<FilterExecution> FilterExecutions { get; set; }
    }
}
