//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("FilterExecution", Schema = "MardisCore")]
    public partial class FilterExecution : IEntity
    {
       
        public FilterExecution()
        {
            this.FilterExecutionDetails = new HashSet<FilterExecutionDetail>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdFilterController { get; set; }
        public Nullable<System.DateTime> DateInit { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public System.Guid IdUser { get; set; }
        public Nullable<System.DateTime> LastExecution { get; set; }
    
       
        public virtual ICollection<FilterExecutionDetail> FilterExecutionDetails { get; set; }

        [ForeignKey("IdFilterController")]
        public virtual FilterController FilterControllers { get; set; }
    }
}
