//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("FilterField", Schema = "MardisCore")]
    public partial class FilterField : IEntity
    {
        
        public FilterField()
        {
            this.FilterCriterias = new HashSet<FilterCriteria>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdFilterController { get; set; }
        public System.Guid IdFilterTable { get; set; }
        public string Field { get; set; }
        public string TypeField { get; set; }
        public string FieldDescription { get; set; }
        public string Visible { get; set; }



        [ForeignKey("IdFilterController")]
        public virtual FilterController FilterController { get; set; }
        public virtual ICollection<FilterCriteria> FilterCriterias { get; set; }
        [ForeignKey("IdFilterTable")]
        public virtual FilterTable FilterTable { get; set; }
    }
}
