//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("FilterExecutionDetail", Schema = "MardisCore")]
    public partial class FilterExecutionDetail : IEntity
    {
        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdFilterExecution { get; set; }
        public System.Guid IdFilterCriteria { get; set; }
        public string Value { get; set; }
        public DateTime CreationFilter { get; set; }

        [ForeignKey("IdFilterExecution")]
        public virtual FilterExecution FilterExecution { get; set; }
        [ForeignKey("IdFilterCriteria")]
        public virtual FilterCriteria FilterCriteria { get; set; }
    }
}
