//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("FilterCriteria", Schema = "MardisCore")]
    public partial class FilterCriteria : IEntity
    {
        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdFilterField { get; set; }
        public System.Guid IdTypeFilter { get; set; }



        [ForeignKey("IdFilterField")]
        public virtual FilterField FilterField { get; set; }
        [ForeignKey("IdTypeFilter")]
        public virtual TypeFilter TypeFilter { get; set; }
        public virtual ICollection<FilterExecutionDetail> FilterExecutionDetails { get; set; }
    }
}
