//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("TypeFilter", Schema = "MardisCore")]
    public partial class TypeFilter : IEntity
    {
        
        public TypeFilter()
        {
            this.FilterCriterias = new HashSet<FilterCriteria>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public string SignFilter { get; set; }
        public string Name { get; set; }
    
      
        public virtual ICollection<FilterCriteria> FilterCriterias { get; set; }
    }
}
