//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    [Table("TypePoll", Schema = "MardisCore")]
    public partial class TypePoll: IEntity, ISoftDelete
    {
        
        public TypePoll()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string StatusRegister { get; set; }
        public string Code { get; set; }
    
       

        public virtual ICollection<Question> Questions { get; set; }
    }
}
