//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mardis.Engine.DataAccess.MardisCore
{
    /// <summary>
    /// Tipo de Cliente por Cuenta en el Sistema
    /// </summary>
    [Table("TypeCustomer", Schema = "MardisCore")]
    public partial class TypeCustomer : IEntity, ISoftDelete
    {
       
        public TypeCustomer()
        {
            this.Customers = new HashSet<Customer>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string StatusRegister { get; set; }

        public virtual ICollection<Customer> Customers { get; set; }
    }
}
