CREATE TABLE [MardisCore].[Branch]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [IdAccount] UNIQUEIDENTIFIER NOT NULL, 
    [Code] VARCHAR(50) NOT NULL, 
	[ExternalCode] VARCHAR(20) NULL, 
    [Name] VARCHAR(200) NOT NULL, 
	[Label] VARCHAR(200) NOT NULL, 
    [CreationDate] DATETIME NOT NULL, 
    [IdCountry] UNIQUEIDENTIFIER NOT NULL, 
    [IdProvince] UNIQUEIDENTIFIER NOT NULL, 
    [IdDistrict] UNIQUEIDENTIFIER NOT NULL, 
    [IdParish] UNIQUEIDENTIFIER NOT NULL, 
    [IdSector] UNIQUEIDENTIFIER NOT NULL, 
    [Zone] VARCHAR(250) NOT NULL, 
    [Neighborhood] VARCHAR(250) NOT NULL, 
    [MainStreet] VARCHAR(250) NOT NULL, 
    [SecundaryStreet] VARCHAR(250) NOT NULL, 
    [NumberBranch] VARCHAR(100) NOT NULL, 
    [LatitudeBranch] VARCHAR(250) NOT NULL, 
    [LenghtBranch] VARCHAR(250) NOT NULL, 
    [Reference] VARCHAR(500) NOT NULL, 
    [IdPersonOwner] UNIQUEIDENTIFIER NOT NULL, 
    [IsAdministratorOwner] VARCHAR(2) NOT NULL, 
    [IdPersonAdministrator] UNIQUEIDENTIFIER NULL, 
    [StatusRegister] VARCHAR(20) NOT NULL, 
    [TypeBusiness] VARCHAR(250),
    [ESTADOAGGREGATE] NCHAR(1) NULL, 
    [RUTAAGGREGATE] VARCHAR(500) NULL, 
    [IMEID_ID] VARCHAR(50) NULL, 
    CONSTRAINT [FK_Branch_Country] FOREIGN KEY (IdCountry) REFERENCES MardisCommon.Country(Id), 
    CONSTRAINT [FK_Branch_Province] FOREIGN KEY (IdProvince) REFERENCES MardisCommon.Province(Id), 
    CONSTRAINT [FK_Branch_District] FOREIGN KEY ([IdDistrict]) REFERENCES MardisCommon.District(Id),
	CONSTRAINT [FK_Branch_Parish] FOREIGN KEY ([IdParish]) REFERENCES MardisCommon.Parish(Id),
	CONSTRAINT [FK_Branch_Sector] FOREIGN KEY ([IdSector]) REFERENCES MardisCommon.Sector(Id), 
    CONSTRAINT [FK_Branch_PersonOwner] FOREIGN KEY ([IdPersonOwner]) REFERENCES MardisCommon.Person([Id]),
	CONSTRAINT [FK_Branch_PersonAdministrator] FOREIGN KEY ([IdPersonAdministrator]) REFERENCES MardisCommon.Person([Id])
)
