CREATE TABLE [MardisCore].[Task]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [IdAccount] UNIQUEIDENTIFIER NOT NULL, 
    [Code] NCHAR(10) NOT NULL, 
	[ExternalCode] NCHAR(20) NOT NULL, 
    [DateCreation] DATE NOT NULL, 	
    [DateModification] DATEtime NOT NULL default(getdate()), 
	[IdCampaign] UNIQUEIDENTIFIER NOT NULL, 
	[StartDate] DATETIME NOT NULL,
	[Description] VARCHAR(250) NOT NULL,
	[IdBranch] UNIQUEIDENTIFIER NOT NULL, 
	[IdMerchant] UNIQUEIDENTIFIER NOT NULL, 
	[StatusRegister] VARCHAR(20) NOT NULL,
	[IdStatusTask] UNIQUEIDENTIFIER NOT NULL, 
	[CommentTaskNoImplemented] VARCHAR(20),
	[IdTaskNoImplementedReason] UNIQUEIDENTIFIER, 
	[Route] VARCHAR(50) NULL, 
    [AggregateUri] VARCHAR(100) NULL, 
    [UserValidator] UNIQUEIDENTIFIER NULL, 
    [DateValidation] DATETIME NOT NULL DEFAULT (getdate()), 
    CONSTRAINT [FK_Task_Account] FOREIGN KEY (IdAccount) REFERENCES MardisCommon.Account(Id),
	CONSTRAINT [FK_Task_Campaign] FOREIGN KEY (IdCampaign) REFERENCES MardisCore.Campaign(Id),
	CONSTRAINT [FK_Task_Branch] FOREIGN KEY (IdBranch) REFERENCES MardisCore.Branch(Id),
	CONSTRAINT [FK_Task_Merchant] FOREIGN KEY (IdMerchant) REFERENCES MardisSecurity.[User](Id),
	CONSTRAINT [FK_Task_StatusTask] FOREIGN KEY (IdStatusTask) REFERENCES MardisCore.StatusTask(Id),
	CONSTRAINT [FK_Task_TaskNotImplementedReason] FOREIGN KEY (IdTaskNoImplementedReason) REFERENCES MardisCore.TaskNoImplementedReason(Id),
	CONSTRAINT [FK_Task_Validator] FOREIGN KEY (UserValidator) REFERENCES MardisSecurity.[User](Id)
)
