//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Mardis.Engine.DataAccess.MardisCore;

namespace Mardis.Engine.DataAccess.MardisCommon
{
    /// <summary>
    /// Tabla de Paises
    /// </summary>
    [Table("Country", Schema = "MardisCommon")]
    public partial class Country : IEntity, ISoftDelete
    {
       
        public Country()
        {
            this.Branches = new HashSet<Branch>();
            this.Provinces = new HashSet<Province>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string StatusRegister { get; set; }
    
      
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
