//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Mardis.Engine.DataAccess.MardisCore;

namespace Mardis.Engine.DataAccess.MardisCommon
{
    /// <summary>
    /// Distritos (Cantones) en el Sistema
    /// </summary>
    [Table("District", Schema = "MardisCommon")]
    public partial class District : IEntity, ISoftDelete
    {
       
        public District()
        {
            this.Branches = new HashSet<Branch>();
            this.Sectors = new HashSet<Sector>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdProvince { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string StatusRegister { get; set; }

        public long? IdManagement { get; set; }

        [ForeignKey("IdManagement")]
        public Management Management { get; set; }

        public virtual ICollection<Branch> Branches { get; set; }
        [ForeignKey("IdProvince")]
        public virtual Province Province { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
    }
}
