//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Mardis.Engine.DataAccess.MardisCore;

namespace Mardis.Engine.DataAccess.MardisCommon
{
    /// <summary>
    /// Provincias en el Sistema
    /// </summary>
    [Table("Province", Schema = "MardisCommon")]
    public partial class Province : IEntity
    {
       
        public Province()
        {
            this.Districts = new HashSet<District>();
            this.Branches = new HashSet<Branch>();
        }
    
        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdCountry { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }

        [ForeignKey("IdCountry")]
        public virtual Country Country { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
