//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Mardis.Engine.DataAccess.MardisCore;

namespace Mardis.Engine.DataAccess.MardisCommon
{
    /// <summary>
    /// Sectores en el Sistema
    /// </summary>
    [Table("Sector", Schema = "MardisCommon")]
    public partial class Sector : IEntity, ISoftDelete
    {
       
        public Sector()
        {
            this.Branches = new HashSet<Branch>();
        }

        [Key]
        public System.Guid Id { get; set; }
        public System.Guid IdDistrict { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string StatusRegister { get; set; }

        [ForeignKey("IdDistrict")]
        public virtual District District { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
